
DROP TABLE T_MOVEMENT;

DROP TABLE T_CLI_CTA;

DROP TABLE T_ACCOUNT;

DROP TABLE T_CLIENT ;

DROP TABLE T_PERSON;

CREATE TABLE T_PERSON (
	PERSONID NUMBER(18) NOT NULL,
	IDENTIFY VARCHAR(15) NOT NULL,
	TYPEIDENTIFY VARCHAR(25) NOT NULL,
	NAMES VARCHAR(60) NOT NULL,
	GENDER VARCHAR(15),
	AGE NUMBER(3),
	ADDRESS VARCHAR(100),
	PHONE VARCHAR(20),
	CONSTRAINT T_PERSON_PK PRIMARY KEY (PERSONID)
);
CREATE UNIQUE INDEX T_PERSON_PRIMARY_KEY ON T_PERSON (PERSONID);
CREATE UNIQUE INDEX T_PERSON_IDENTIFY_IDX ON T_PERSON (IDENTIFY,TYPEIDENTIFY);


CREATE TABLE T_CLIENT (
	CLIENTID NUMBER(18) NOT NULL,
	PASSWORD VARCHAR(100),
	STATUS NUMBER(1) NOT NULL,
	CONSTRAINT T_CLIENT_PK PRIMARY KEY (CLIENTID),
	CONSTRAINT T_CLIENT_T_PERSON_FK FOREIGN KEY (CLIENTID) REFERENCES T_PERSON(PERSONID) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE UNIQUE INDEX T_CLIENT_PRIMARY_KEY ON T_CLIENT (CLIENTID);

CREATE TABLE T_ACCOUNT (
	ACCOUNTNUMBER NUMBER(18) NOT NULL,
	TYPEACCOUNT VARCHAR(20) NOT NULL,
	SALTINI NUMBER(18,7),
	STATUS NUMBER(1) NOT NULL,
	CONSTRAINT T_ACCOUNT_PK PRIMARY KEY (ACCOUNTNUMBER)
);
CREATE UNIQUE INDEX T_ACCOUNT_PRIMARY_KEY ON T_ACCOUNT (ACCOUNTNUMBER);

CREATE TABLE T_CLI_CTA (
	ACCOUNTNUMBER NUMBER(18) NOT NULL,
	CLIENTID NUMBER(18) NOT NULL,
	CONSTRAINT T_CLI_CTA_PK PRIMARY KEY (ACCOUNTNUMBER,CLIENTID),
	CONSTRAINT T_CLI_CTA_T_ACCOUNT_FK FOREIGN KEY (ACCOUNTNUMBER) REFERENCES T_ACCOUNT(ACCOUNTNUMBER) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT T_CLI_CTA_T_CLIENT_FK FOREIGN KEY (CLIENTID) REFERENCES T_CLIENT(CLIENTID) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE UNIQUE INDEX T_CLI_CTA_PRIMARY_KEY ON T_CLI_CTA (ACCOUNTNUMBER,CLIENTID);
CREATE INDEX T_CLI_CTA_T_ACCOUNT_FK_INDEX ON T_CLI_CTA (ACCOUNTNUMBER);
CREATE INDEX T_CLI_CTA_T_CLIENT_FK_INDEX ON T_CLI_CTA (CLIENTID);


CREATE TABLE T_MOVEMENT (
	IDMOVEMENT NUMBER(18) NOT NULL,
	ACCOUNTNUMBER NUMBER(18) NOT NULL,
	DATEFROM TIMESTAMP NOT NULL,
	TYPEMOVEMENT VARCHAR(20) NOT NULL,
	VALUEAMOUNT NUMBER(18,7) NOT NULL,
	SALTAMOUNT NUMBER(18,7) NOT NULL,
	CONSTRAINT T_MOVEMENT_PK PRIMARY KEY (IDMOVEMENT),
	CONSTRAINT T_MOVEMENT_T_ACCOUNT_FK FOREIGN KEY (ACCOUNTNUMBER) REFERENCES T_ACCOUNT(ACCOUNTNUMBER) ON DELETE RESTRICT ON UPDATE RESTRICT
);
CREATE UNIQUE INDEX T_MOVEMENT_PRIMARY_KEY ON T_MOVEMENT (IDMOVEMENT);
CREATE INDEX T_MOVEMENT_T_ACCOUNT_FK_INDEX ON T_MOVEMENT (ACCOUNTNUMBER);
